### PR TITLE
8.0 nhomar lookandfeel

### PR DESCRIPTION
**Pull request by nhomar**
It is a WIP, just the PR to have comments.

The plan.

Plan

How it goes.

result

@moylop260 Comments?

### CODE REVIEW

**Comment by moylop260** [comment]
Looks fine.
Where I can test it?

**Comment by moylop260** [comment]
My feedback
feedback

**Comment by moylop260** [comment]
==Offtopic==
Order by name in team selection:
team order by

**Comment by moylop260** [comment]
remove button action (not push option)
descarga 5

**Comment by nhomar** [comment]
About: https://github.com/Vauxoo/odoo-extra/pull/31#issuecomment-90944240

The link is already unique in the view and can be related copying as before, just the ID is an ID number not a text which bring problems with the relation and parsing (see image).

img0

About branch name -- DONE.

Some other improvements like icon to know where is the branch linked to (Github, Bitbucket supported, LP just informed).

Some other improvements done.

@moylop260 - IMHO it can be merged already, I can continue the Offtopic part in other PR.

**Pull request merged**
