### PR TITLE
[ADD] add new filter to search by SHA in the build view.

### PR DESCRIPTION
**Pull request by zaoral**
Task [vx#3914](https://www.vauxoo.com/web#id=3914&view_type=form&model=project.task&action=138)

### CODE REVIEW

**Comment by zaoral** [comment]
Waiting for testing tools

**Comment by zaoral** [comment]
@moylop260 Vauxoo production instance odoo-extra branch is the 8.0-vauxoo branch?
Best regards.

**Comment by moylop260** [comment]
@zaoral yes

**Comment by zaoral** [comment]
ok. perfect. thanks @moylop260

**Pull request merged**
